apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flask-deploy
  name: flask-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flask-deploy
    spec:
      containers:
      - image: rohitraut3366/flask-basic:v3
        name: flask-basic
        resources: {}
status: {}
